### ISSUE TITLE
Implement authorization tokens

### ISSUE THREAD

**Issue by ethangreen-dev** [StochSS/stochss-compute#14]
Authorization tokens would be used to ensure that access to the compute resources of a stochss-compute instance is restricted to certain users. These tokens would be passed to the server via the RemoteSimulation class. 

- [ ] Implement secure token generation.
- [ ] Add infrastructure to store user tokens.
- [ ] Implement session token generation -- we don't want to be passing auth tokens back and forth.
- [ ] Modifications to the API to support session and authentication tokens.
- [ ] Possible encrypted communication.
- [ ] Add distinction between normal and administrator users. 
- [ ] Add API endpoints for administrator access: Adding users, removing users, etc.
- [ ] Add session and authentication token support to the `RemoteSimulation` client.

**Comment by briandrawert** [comment]
Not all these need to be implemented by 1.0
