### ISSUE TITLE
Update Notebook

### ISSUE THREAD

**Issue by seanebum** [StochSS/stochss-compute#152]
Tutorial_1-local is not working correctly right now.

- Section 7 needs to be updated, integrator options are outdated, show_labels is depricated
- Error is thrown on SubProcess command - file not found.  SubProcess should not be called within the notebook and should be called inside of a command that can handle the file location appropriately.  See screenshot for details
<img width="1792" alt="Screen Shot 2022-10-26 at 3 52 12 PM" src="https://user-images.githubusercontent.com/22843486/198124484-7f309105-0595-49e3-83a2-60e346dfa3ef.png">

**Comment by mdip226** [comment]
change to `python -m stochss_compute.launch cluster `
