### ISSUE TITLE
error when running a later instance on bare metal

### ISSUE THREAD

**Issue by mdip226** [StochSS/stochss-compute#41]
I just remembered that I was getting an error when running a later instance of compute on bare metal. The vault had not been cleared so when I ran the same model on the second instance it was throwing an error, I think trying to reference the old results hash that it recognized as being in it's cache. I still need to go back and reproduce the error but I wanted to make an issue so that I won't forget.  Not sure what the correct behavior would be here but I'm thinking the cache should still work even if it is not cleared between restarts.

**Comment by briandrawert** [comment]
Do we need to remove all references to the 'vault'?
