### ISSUE TITLE
Dask client instantiation references an invalid DaskDelegateConfig property 

### ISSUE THREAD

**Issue by ethangreen-dev** [StochSS/stochss-compute#48]
This sources from `self.client = Client(self.delegate_config.cluster_address)`, `cluster_address` is not a member of `DaskDelegateConfig`, it should actually be `self.client = Client(cluster_address)`, where `cluster_address = $"{self.delegate_config.dask_cluster_address}:{self.delegate_config.dask_cluster_port}"`

**Comment by mdip226** [comment]
ah, I see. Thanks for getting that
